package workermanagement.model;
// Generated Dec 13, 2015 4:40:24 PM by Hibernate Tools 4.3.1

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;




/**
 * Unit generated by hbm2java and modified to contain properties for display in table views
 */
public class Unit  implements java.io.Serializable {


     private final IntegerProperty id;
     private final StringProperty name;

    /**
     * Unit constructor
     * @param id the id for the Unit
     * @param name the name for the Unit
     */
    public Unit(int id, String name) {
       this.id = new SimpleIntegerProperty(id);
       this.name = new SimpleStringProperty(name);
    }
    
    /**
     * Unit constructor
     * @param name the name for the Unit
     */
    public Unit(String name) {
        this(0, name);
    }

    /**
     * Default unit constructor
     */
    public Unit() {
        this(0, "");
    }
    
    /**
     * 
     * @return IntegerProperty
     */
    public IntegerProperty idProperty() {
        return this.id;
    }
   
    /**
     *
     * @return int
     */
    public int getId() {
        return this.idProperty().get();
    }
    
    /**
     *
     * @param id the value to assign to the id
     */
    public void setId(int id) {
        this.idProperty().set(id);
    }
    
    /**
     *
     * @return StringProperty
     */
    public StringProperty nameProperty() {
        return this.name;
    }
    
    /**
     *
     * @return String
     */
    public String getName() {
        return this.nameProperty().get();
    }
    
    /**
     *
     * @param name the value to assign to the name
     */
    public void setName(String name) {
        this.nameProperty().set(name);
    }

     @Override
    public String toString() {
        return this.getName();
    }

     @Override
    public boolean equals(Object obj) {
        if(obj == null || !(obj instanceof Unit))
            return false;
        Unit u = (Unit) obj;
        return u.getId() == this.getId() || u.getName().equals(this.getName());
    }

}


