package workermanagement.model;
// Generated Dec 13, 2015 5:24:14 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Workitem generated by hbm2javaand modified to contain properties for display in table views
 */
public class Workitem implements java.io.Serializable {


     private final IntegerProperty id;
     private final SimpleObjectProperty<Date> date;
     private final SimpleObjectProperty<BigDecimal> rate;
     private final SimpleObjectProperty<BigDecimal> qty;
     private final SimpleObjectProperty<BigDecimal> total;
     private final IntegerProperty workerid;
     private final IntegerProperty unitid;
     private final StringProperty unitname;
     private Unit unit;

    /**
     * Workitem constructor
     * @param id the Workitem id
     * @param date the Workitem date
     * @param rate the Workitem rate
     * @param qty the Workitem quantity
     * @param workerid the Workitem worker id
     * @param unit the Workitem unit id
     */
    public Workitem(int id, Date date, BigDecimal rate, BigDecimal qty, int workerid, Unit unit) {
       if(unit == null) unit = new Unit();
       this.id = new SimpleIntegerProperty(id);
       this.date = new SimpleObjectProperty<Date>(date);
       this.rate = new SimpleObjectProperty<BigDecimal>(rate);
       this.qty = new SimpleObjectProperty<BigDecimal>(qty);
       this.total = new SimpleObjectProperty<BigDecimal>(qty.multiply(rate));
       this.workerid = new SimpleIntegerProperty(workerid);
       this.unitid = new SimpleIntegerProperty(unit.getId());
       this.unit = unit;
       this.unitname = new SimpleStringProperty(unit.getName());
    }
    
    /**
     * Workitem Constructor
     * @param id the Workitem id
     * @param date the Workitem date
     * @param rate the Workitem rate
     * @param qty the Workitem quantity
     * @param workerid the Workitem worker id
     * @param unitid the Workitem unit id
     */
    public Workitem(int id, Date date, BigDecimal rate, BigDecimal qty, int workerid, int unitid) {
        this(id, date, rate, qty, workerid, WorkHelper.getUnitById(unitid));
    }

    /**
     * Default workitem constructor
     */
    public Workitem() {
        this(0, new Date(), new BigDecimal(0), new BigDecimal(0), 0, null);
    }
    
    /**
     * Converts SimpleObjectProperties of any type to SimpleStringProperties
     * @return SimpleStringProperty
     */
    private SimpleStringProperty getStringProperty(SimpleObjectProperty<?> prop) {
        return new SimpleStringProperty(prop.getValue().toString());
    }
    
    /**
     *
     * @return IntegerProperty
     */
    public IntegerProperty idProperty() {
        return this.id;
    }
   
    /**
     *
     * @return int
     */
    public int getId() {
        return this.idProperty().get();
    }
    
    /**
     *
     * @param id the value to assign to the id
     */
    public void setId(int id) {
        this.idProperty().set(id);
    }
    
    /**
     *
     * @return SimpleObjectProperty of Date type
     */
    public SimpleObjectProperty<Date> dateProperty() {
        return this.date;
    }
    
    /**
     *
     * @return SimpleStringProperty
     */
    public SimpleStringProperty dateStringProperty() {
        return this.getStringProperty(this.date);
    }
    
    /**
     *
     * @return Date
     */
    public Date getDate() {
        return this.dateProperty().get();
    }
    
    /**
     *
     * @param date the value to assign to the date
     */
    public void setDate(Date date) {
        this.dateProperty().set(date);
    }
    
    /**
     *
     * @return SimpleObjectProperty of BigDecimal type
     */
    public SimpleObjectProperty<BigDecimal> rateProperty() {
        return this.rate;
    }
    
    /**
     *
     * @return SimpleStringProperty
     */
    public SimpleStringProperty rateStringProperty() {
        return this.getStringProperty(this.rate);
    }
    
    /**
     *
     * @return BigDecimal
     */
    public BigDecimal getRate() {
        return this.rateProperty().get();
    }
    
    /**
     *
     * @param rate the value to assign to the rate
     */
    public void setRate(BigDecimal rate) {
        this.rateProperty().set(rate);
        this.setTotal();
    }
    
    /**
     *
     * @return SimpleObjectProperty of BigDecimal type
     */
    public SimpleObjectProperty<BigDecimal> qtyProperty() {
        return this.qty;
    }
    
    /**
     *
     * @return SimpleStringProperty
     */
    public SimpleStringProperty qtyStringProperty() {
        return this.getStringProperty(this.qty);
    }
    
    /**
     *
     * @return BigDecimal
     */
    public BigDecimal getQty() {
        return this.qtyProperty().get();
    }
    
    /**
     *
     * @param qty the value to assign to the quantity
     */
    public void setQty(BigDecimal qty) {
        this.qtyProperty().set(qty);
        this.setTotal();
    }
    
    /**
     *
     * @return SimpleObjectProperty of BigDecimal type
     */
    public SimpleObjectProperty<BigDecimal> totalProperty() {
        return this.total;
    }
    
    /**
     *
     * @return SimpleStringProperty
     */
    public SimpleStringProperty totalStringProperty() {
        return this.getStringProperty(this.total);
    }
    
    private void setTotal() {
        this.totalProperty().set(this.qtyProperty().get().multiply(
            this.rateProperty().get()));
    }
    
    /**
     *
     * @return IntegerProperty
     */
    public IntegerProperty workeridProperty() {
        return this.workerid;
    }
    
    /**
     *
     * @return int
     */
    public int getWorkerid() {
        return this.workeridProperty().get();
    }
    
    /**
     *
     * @param workerid the value to assign to the workerid
     */
    public void setWorkerid(int workerid) {
        this.workeridProperty().set(workerid);
    }
    
    /**
     *
     * @return the unitid as an IntegerProperty
     */
    public IntegerProperty unitidProperty() {
        return this.unitid;
    }
    
    /**
     *
     * @return int
     */
    public int getUnitid() {
        return this.unitidProperty().get();
    }
    
    /**
     *
     * @param unitid the value to assign to the unitid
     */
    public void setUnitid(int unitid) {
        this.unitidProperty().set(unitid);
    }

    /**
     *
     * @return StringProperty
     */
    public StringProperty unitnameProperty() {
        return new SimpleStringProperty(this.unit.getName());
    }
    
    /**
     *
     * @return String
     */
    public String getUnitname() {
        return this.unitnameProperty().get();
    }

    /**
     *
     * @return Unit
     */
    public Unit getUnit() {
        return unit;
    }

    /**
     *
     * @param unit the value to assign to the unit
     */
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
}


